### PR TITLE
Dummy changes for CI tests

### PR DESCRIPTION
**Pull request by asmorkalov**

### CODE REVIEW

**Comment by evgeny-izutov** [comment]
@asmorkalov Do we need merge it after #3?

**Comment by asmorkalov** [comment]
No, please do not touch it. I need opened PR to trigger CI jobs and test infra part.

**Comment by asmorkalov** [comment]
Jenkins please retry a build

**Comment by asmorkalov** [comment]
Jenkins please retry a build

**Comment by asmorkalov** [comment]
Jenkins please retry a build

**Comment by asmorkalov** [comment]
Jenkins please retry a build

**Comment by asmorkalov** [comment]
@evgeny-izutov please take a look at CI logs.

**Pull request closed without merging**
